### PR TITLE
Kürşat's branch

### PR DESCRIPTION
**Pull request by oguz3027**
added new lines

### CODE REVIEW

**Comment by kerimeunal82** [comment]
good job

**Review by ciritbeyi — APPROVED** [review]
well done

**Review by akilealtin — APPROVED** [review]
good jop

**Review by kerimeunal82 — COMMENTED** [review]
good job kürşat

**Comment by EmreKarakus92** [comment]
Good job kursat

**Review by EmreKarakus92 — APPROVED** [review]
Okey

**Pull request merged**
